### ISSUE TITLE
Unable to start the project in local: Couldn't find any `pages` or `app` directory.

### ISSUE THREAD

**Issue by shashankdaima** [dubinc/dub#1010]
I am trying to follow through your https://dub.co/docs/local-development. 
But i am getting this in last step(i.e. when i start the project with `pnpm dev` in `apps/web` in windows machine). 
![image](https://github.com/dubinc/dub/assets/64317542/331da5c6-a553-4021-b322-d3f5f18c95b3)
```
PS C:\Users\Lenovo\dev\dub\apps\web> pnpm run  dev

> web@ dev C:\Users\Lenovo\dev\dub\apps\web
> concurrently --kill-others "prisma generate && next dev --turbo --port 8888" "prisma generate && prisma studio --browser none" "email dev --port 3333"

(node:13580) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2]     React Email 2.0.0
[2] - Getting react-email preview server ready...
[2] 
[2]     Running preview at:          http://localhost:3333
[2] 
[0] Environment variables loaded from .env
[0] Prisma schema loaded from prisma\schema.prisma
[1] Environment variables loaded from .env
[1] Prisma schema loaded from prisma\schema.prisma
[2] Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
[2]     at findPagesDir (C:\Users\Lenovo\dev\dub\node_modules\.pnpm\next@14.0.5-canary.46_@babel+core@7.23.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-pages-dir.js:42:15)
[2]     at initialize (C:\Users\Lenovo\dev\dub\node_modules\.pnpm\next@14.0.5-canary.46_@babel+core@7.23.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:71:69)
[2]     at async NextCustomServer.prepare (C:\Users\Lenovo\dev\dub\node_modules\.pnpm\next@14.0.5-canary.46_@babel+core@7.23.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next.js:240:28)
[2]
[2] shutting down dev server
[2] email dev --port 3333 exited with code 1
--> Sending SIGTERM to other processes..
[0] prisma generate && next dev --turbo --port 8888 exited with code 1
--> Sending SIGTERM to other processes..
[1] prisma generate && prisma studio --browser none exited with code 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by shashankdaima** [comment]
[Update]: this issue was not solvable in windows. I have to use wsl to run this project.
