### ISSUE TITLE
Build Failed due to API error and TypeError

### ISSUE THREAD

**Issue by SANDP1T-Devs** [dubinc/dub#1051]
Hi there, I am encountering these issues when trying to build the latest main@46730c3.

Can I confirm that this is a configuration or code issue?

Thanks so much!

```
API error occurred Dynamic server usage: Route /api/me couldn't be rendered statically because it accessed `request.headers`
API error occurred Dynamic server usage: Route /api/support/upload couldn't be rendered statically because it accessed `request.headers`
```

```
TypeError: Cannot read properties of undefined (reading 'recurring_revenue')
```
```

web:build:  ✓ Linting and checking validity of types 
 ⚠ Using edge runtime on a page currently disables static generation for that page
web:build:  ✓ Collecting page data 
web:build:    Generating static pages (0/62)  [    ]API error occurred Dynamic server usage: Route /api/analytics/demo couldn't be rendered statically because it accessed `request.headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
   Generating static pages (14/62)  [=   ](node:3446) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
web:build: (Use `node --trace-deprecation ...` to show where the warning was created)
web:build: Anonymous analytics enabled. You can disable this by setting the DO_NOT_TRACK=1 or BOXYHQ_NO_ANALYTICS=1 environment variables
web:build: Using engine: planetscale.
   Generating static pages (29/62)  [==  ]API error occurred Dynamic server usage: Route /api/me couldn't be rendered statically because it accessed `request.headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
   Generating static pages (31/62)  [=== ]API error occurred Dynamic server usage: Route /api/support/upload couldn't be rendered statically because it accessed `request.headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
   Generating static pages (55/62)  [    ]TypeError: Cannot read properties of undefined (reading 'recurring_revenue')
web:build:     at p (/workspace/dub/apps/web/.next/server/app/admin.dub.co/revenue/page.js:1:6107)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web:build:   digest: '115075521'
web:build: }
   Generating static pages (61/62)  [ ===]TypeError: Cannot read properties of undefined (reading 'recurring_revenue')
web:build:     at p (/workspace/dub/apps/web/.next/server/app/admin.dub.co/revenue/page.js:1:6107)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web:build:   digest: '115075521'
web:build: }
web:build: TypeError: Cannot read properties of undefined (reading 'recurring_revenue')
web:build:     at p (/workspace/dub/apps/web/.next/server/app/admin.dub.co/revenue/page.js:1:6107)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web:build:   digest: '115075521'
web:build: }
web:build: 
web:build: Error occurred prerendering page "/admin.dub.co/revenue". Read more: https://nextjs.org/docs/messages/prerender-error
web:build: 
web:build: TypeError: Cannot read properties of undefined (reading 'recurring_revenue')
web:build:     at p (/workspace/dub/apps/web/.next/server/app/admin.dub.co/revenue/page.js:1:6107)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ✓ Generating static pages (62/62)
web:build: 
web:build: > Export encountered errors on following paths:
web:build:      /admin.dub.co/revenue/page: /admin.dub.co/revenue
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/workspace/dub/apps/web) /home/gitpod/.nvm/versions/node/v20.15.0/bin/pnpm run build exited (1)
web#build: command (/workspace/dub/apps/web) /home/gitpod/.nvm/versions/node/v20.15.0/bin/pnpm run build exited (1)
```

**Comment by devkiran** [comment]
This has been fixed. Thanks for reporting.
