### ISSUE TITLE
Vercel deployment error - Login not working

### ISSUE THREAD

**Issue by sebiweise** [dubinc/dub#1111]
I´ve just installed/deployed my fork to my Vercel account and everything is working fine, the build is running and also the app., admin. and also api. Subdomains are working and can be accessed.
But when I try to login via Google, after the callback is send, I´m not able to access the dashboard.
In the Vercel logs these errors are showing and in the browser I´m getting a 504 error.
![image](https://github.com/user-attachments/assets/906736dc-8d71-4a0e-9464-5b55b71b3dd4)
Did I miss something?

On first login, the user is created in the database and also my Google profile image is uplaoded to the Cloudflare R2 bucket.

**Comment by sebiweise** [comment]
When I run dub locally I´m getting the following error while creating a workspace:
```
[0] error - TypeError: fetch failed
[0]     at node:internal/deps/undici/undici:12502:13
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async postJSON (C:\Repos\dub\apps\web\.next\server\chunks\08b5e__pnpm_8a0ba3._.js:105938:22)
[0]     at async Connection.execute (C:\Repos\dub\apps\web\.next\server\chunks\08b5e__pnpm_8a0ba3._.js:105891:23)
[0]     at async checkIfUserExists (C:\Repos\dub\apps\web\.next\server\chunks\[project]__11d57b._.js:4195:22)
[0]     at async C:\Repos\dub\apps\web\.next\server\chunks\[project]__11d57b._.js:4744:24
[0]     at async C:\Repos\dub\apps\web\.next\server\chunks\[project]__11d57b._.js:3277:20 {
[0]   [cause]: [Error]
[0] } {
[0]   startTime: 1722078694044,
[0]   endTime: 1722078694365,
[0]   path: '/api/workspaces',
[0]   method: 'POST',
[0]   host: 'localhost:8888',
[0]   userAgent: '****',
[0]   scheme: 'http',
[0]   ip: '::1',
[0]   region: '',
[0]   statusCode: 500,
[0]   durationMs: 321
[0] }
```

Something related to the function checkIfUserExists

**Comment by harshsbhat** [comment]
Hey, so I think this is something that you should put into discussions rather than in issues. As this is an issue on your machine and not the Dub.co codebase
