### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by dor123official** [dubinc/dub#1177]
hello...i got this error when deploy on vercel... 

`[22:19:26.565] web:build:    Collecting page data ...
[22:19:28.195] web:build: TypeError: Invalid URL
[22:19:28.195] web:build:     at new URL (node:internal/url:797:36)
[22:19:28.196] web:build:     at new y (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:16441)
[22:19:28.196] web:build:     at v (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:18473)
[22:19:28.199] web:build:     at 153998 (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:3895)
[22:19:28.200] web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:143)
[22:19:28.200] web:build:     at 952293 (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:5071)
[22:19:28.200] web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:143)
[22:19:28.200] web:build:     at 972139 (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:848)
[22:19:28.200] web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:143)
[22:19:28.200] web:build:     at 14039 (/vercel/path0/apps/web/.next/server/chunks/1252.js:1:114) {
[22:19:28.201] web:build:   code: 'ERR_INVALID_URL',
[22:19:28.201] web:build:   input: '"http://root:unused@localhost:3900"'
[22:19:28.201] web:build: }
[22:19:28.201] web:build: 
[22:19:28.201] web:build: > Build error occurred
[22:19:28.201] web:build: Error: Failed to collect page data for /api/projects/[slug]/domains/[domain]/exists
[22:19:28.202] web:build:     at /vercel/path0/node_modules/.pnpm/next@14.3.0-canary.42_@babel+core@7.23.0_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1267:15
[22:19:28.202] web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[22:19:28.202] web:build:   type: 'Error'
[22:19:28.202] web:build: }
[22:19:28.433] web:build:  ELIFECYCLE  Command failed with exit code 1.
[22:19:28.452] web:build: ERROR: command finished with error: command (/vercel/path0/apps/web) /pnpm9/node_modules/.bin/pnpm run build exited (1)
[22:19:28.452] web#build: command (/vercel/path0/apps/web) /pnpm9/node_modules/.bin/pnpm run build exited (1)
[22:19:28.454] 
[22:19:28.454]   Tasks:    2 successful, 3 total
[22:19:28.455]  Cached:    2 cached, 3 total
[22:19:28.455]    Time:    3m52.555s 
[22:19:28.455] Summary:    /vercel/path0/.turbo/runs/2kZ0oq0mF7K0Xa7oIo5YjcmKea2.json
[22:19:28.455]  Failed:    web#build
[22:19:28.455] 
[22:19:28.459]  ERROR  run failed: command  exited (1)
[22:19:28.522] Error: Command "turbo run build" exited with 1
[22:19:30.551] `

**Comment by dor123official** [comment]
already done
