### ISSUE TITLE
Issue with Local setup

### ISSUE THREAD

**Issue by vignesh-gupta** [dubinc/dub#1782]
Followed the [Dev setup Instructions](https://dub.co/docs/local-development) with docker-compose. 

Issue: Application is starting up and post login with github, getting a weird and unknown error (Disabled other logins from Next-auth Config). 

Error: 
```
⨯ Error [TypeError]: fetch failed
    at context.fetch (file://D:\Codes\dub\node_modules\.pnpm\next@14.3.0-canary.42_@babel+core@7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\web\sandbox\context.js:292:38)
    at postJSON (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:732:28)
7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\web\sandbox\context.js:292:38)
    at postJSON (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:732:28)
    at Connection.execute (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:685:29)
    at Client.execute (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:625:34)
    at PrismaPlanetScale.performIO (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:1376:46)
    at PrismaPlanetScale.queryRaw (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\08b5e__pnpm_f33454._.js:1349:37)
    at <unknown> (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4_@prisma_client_6ee161._.js:1680:26)
    at <unknown> (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4__prisma_client_8936d3._.js:627:24)
    at g (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4__prisma_client_8936d3._.js:276:18)
    at gt (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4__prisma_client_8936d3._.js:626:12)
    at H (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4__prisma_client_8936d3._.js:257:7)
    at f (file://D:\Codes\dub\apps\web\.next\server\edge\chunks\ssr\eeea4__prisma_client_8936d3._.js:249:20)

```

**Comment by subhayand10** [comment]
@vignesh-gupta any solutions for this?
