### ISSUE TITLE
Got SSL Issue when Dockerize Next Build

### ISSUE THREAD

**Issue by reynldi** [dubinc/dub#1799]
I experienced SSL Issue when Dockerize Next Build.

**Important Notes**
- I created Dockerfile and do `turbo run build` there
- Additional env `NODE_ENV=production` and `NEXT_PUBLIC_VERCEL_ENV=production`
- Pointing `DATABASE_URL` and `PLANETSCALE_DATABASE_URL` into my own mysql server
- Nginx proxy with Let's encrypt 

```
Error: fetch failed
    at context.fetch (/app/node_modules/.pnpm/next@14.3.0-canary.42_@babel+core@7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:292:38)
    at tn (/app/apps/web/.next/server/middleware.js:2:22216)
    at tr.execute (/app/apps/web/.next/server/middleware.js:2:21272)
    at aq (/app/apps/web/.next/server/middleware.js:10:55969)
    at sd (/app/apps/web/.next/server/middleware.js:10:66228)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async eT (/app/apps/web/.next/server/middleware.js:2:14896)
    at async /app/node_modules/.pnpm/next@14.3.0-canary.42_@babel+core@7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22
    at async runWithTaggedErrors (/app/node_modules/.pnpm/next@14.3.0-canary.42_@babel+core@7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async NextNodeServer.runMiddleware (/app/node_modules/.pnpm/next@14.3.0-canary.42_@babel+core@7.24.5_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:1061:24) {
  cause: [Error: 58C25FABAA2A0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

**Comment by reynldi** [comment]
Fixed after drop existing schema and do `pnpm run prisma:generate` and `pnpm run prisma:push`

Hope it can be better and more backward-compatible.

Thanks
