### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nhathoagn** [dubinc/dub#713]
Error evaluating Node.js code
Error: Failed to load external module C:\Users\nhathoang\Documents\dub\apps\web/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [C:\Users\nhathoang\Documents\dub\apps\web\.next\chunks\[output]__next_transform_419183.js:1328:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (apps/web/postcss.config.js_.loader.mjs:3:13) [C:\Users\nhathoang\Documents\dub\apps\web\.next\chunks\[project]_apps_web_8e2871._.js:11:13]

node: v20.12.0
branch: main
os: windows 10

**Comment by steven-tey** [comment]
closing due to lack of infromation
