### ISSUE TITLE
Error with new database

### ISSUE THREAD

**Issue by jaiveertalwar** [dubinc/dub#845]
No short links open. Console gives: 
API error occurred TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11731:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (/var/task/apps/web/.next/server/chunks/3412.js:1:3083)
    at async g.execute (/var/task/apps/web/.next/server/chunks/3412.js:1:2146)
    at async l (/var/task/apps/web/.next/server/chunks/1678.js:1:912)
    at async u.needNotExceededClicks (/var/task/apps/web/.next/server/app/api/analytics/[endpoint]/route.js:1:3155)
    at async /var/task/apps/web/.next/server/chunks/9265.js:1:17960
    at async /var/task/node_modules/.pnpm/next@14.2.0-canary.67_@babel+core@7.23.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34801
    at async eS.execute (/var/task/node_modules/.pnpm/next@14.2.0-canary.67_@babel+core@7.23.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25910)
    at async eS.handle (/var/task/node_modules/.pnpm/next@14.2.0-canary.67_@babel+core@7.23.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36055) {
  cause: [Error: C03F0609AF7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:355:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}

**Comment by devkiran** [comment]
Seems like a database connection issue. Can you confirm your database connection is working fine?

**Comment by jaiveertalwar** [comment]
I am able to connect fine from my machine without any ssl issues warns. i have tried a new db also. same error.

**Comment by Skarf4U** [comment]
Have you managed to solve this? My issue is similar, I'm unable to create links, I am however able to create tags, but I get "fetch failed" for adding a link. It works fine locally though, super annoying.

**Comment by jaiveertalwar** [comment]
No unfortunately I have not managed. My old deployment, from a three month old fork of the project displays projects correctly but does not display links within the project. Fortunately links still work. On a new fork of the project, the links don’t work also. I’m currently using the old project since my links are used across a variety of places.
